# Generated by Django 3.1.5 on 2021-03-20 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='p_code',
        ),
    ]
