# Generated by Django 3.1.6 on 2021-04-29 17:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0003_product_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='p_creation_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='p_summary',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='p_description',
            field=models.CharField(max_length=5000),
        ),
    ]
