# Generated by Django 3.1.6 on 2021-05-17 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0004_auto_20210429_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='p_description',
            field=models.CharField(max_length=7500),
        ),
    ]
